
project_id = "rnldyomnsqelvyakpvnk"

[auth]
enabled = true
# Remove deprecated configurations that cause warnings
# GOTRUE_JWT_DEFAULT_GROUP_NAME and GOTRUE_JWT_ADMIN_GROUP_NAME are no longer supported

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false

[auth.external.google]
enabled = false

[auth.external.github]
enabled = false

[db]
pooler_enabled = false

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[analytics]
enabled = false
