// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnldyomnsqelvyakpvnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJubGR5b21uc3FlbHZ5YWtwdm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTU3OTMsImV4cCI6MjA2NjI5MTc5M30.RdNVc7MxpBUSkMcsd88vSp41qRlcpjeb8bzYVij82Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);